"""Protocol Functions Package"""

from .uniswap import UNISWAP_FUNCTIONS
from .aave import AAVE_FUNCTIONS
from .maker import MAKER_FUNCTIONS
from .lido import LIDO_FUNCTIONS
from .curve import CURVE_FUNCTIONS
from .bridges import BRIDGE_FUNCTIONS
from .compound import COMPOUND_FUNCTIONS
from .balancer import BALANCER_FUNCTIONS
from .sushiswap import SUSHISWAP_FUNCTIONS
from .yearn import YEARN_FUNCTIONS
from .bridges_extended import BRIDGE_EXTENDED_FUNCTIONS
from .liquid_staking import LIQUID_STAKING_FUNCTIONS
from .restaking import RESTAKING_FUNCTIONS
from .traditional_staking import TRADITIONAL_STAKING_FUNCTIONS
from .launchpads import LAUNCHPAD_FUNCTIONS
from .additional_dex import ADDITIONAL_DEX_FUNCTIONS
from .stakestone import STAKESTONE_FUNCTIONS
from .mantle_lsp import MANTLE_LSP_FUNCTIONS
from .oneinch import ONEINCH_FUNCTIONS
from .frax_extended import FRAX_EXTENDED_FUNCTIONS
from .ankr_extended import ANKR_EXTENDED_FUNCTIONS
from .stakewise_extended import STAKEWISE_EXTENDED_FUNCTIONS
from .dydx import DYDX_FUNCTIONS
from .bridges.hop import HOP_FUNCTIONS
from .bridges.across import ACROSS_FUNCTIONS
from .bridges.synapse import SYNAPSE_FUNCTIONS
from .dex.hashflow import HASHFLOW_FUNCTIONS
from .dex.maverick import MAVERICK_FUNCTIONS
from .staking.rocketpool import ROCKETPOOL_FUNCTIONS
from .token.create import TOKEN_CREATION_FUNCTIONS
from .gaming import GAMING_PROTOCOLS

PROTOCOLS = {
    'UNISWAP': UNISWAP_FUNCTIONS,
    'AAVE': AAVE_FUNCTIONS,
    'MAKER': MAKER_FUNCTIONS,
    'LIDO': LIDO_FUNCTIONS,
    'CURVE': CURVE_FUNCTIONS,
    'BRIDGES': BRIDGE_FUNCTIONS,
    'COMPOUND': COMPOUND_FUNCTIONS,
    'BALANCER': BALANCER_FUNCTIONS,
    'SUSHISWAP': SUSHISWAP_FUNCTIONS,
    'YEARN': YEARN_FUNCTIONS,
    'BRIDGES_EXTENDED': BRIDGE_EXTENDED_FUNCTIONS,
    'LIQUID_STAKING': LIQUID_STAKING_FUNCTIONS,
    'RESTAKING': RESTAKING_FUNCTIONS,
    'TRADITIONAL_STAKING': TRADITIONAL_STAKING_FUNCTIONS,
    'LAUNCHPADS': LAUNCHPAD_FUNCTIONS,
    'ADDITIONAL_DEX': ADDITIONAL_DEX_FUNCTIONS,
    'STAKESTONE': STAKESTONE_FUNCTIONS,
    'MANTLE_LSP': MANTLE_LSP_FUNCTIONS,
    'ONEINCH': ONEINCH_FUNCTIONS,
    'FRAX_EXTENDED': FRAX_EXTENDED_FUNCTIONS,
    'ANKR_EXTENDED': ANKR_EXTENDED_FUNCTIONS,
    'STAKEWISE_EXTENDED': STAKEWISE_EXTENDED_FUNCTIONS,
    'DYDX': DYDX_FUNCTIONS,
    'HOP': HOP_FUNCTIONS,
    'ACROSS': ACROSS_FUNCTIONS,
    'SYNAPSE': SYNAPSE_FUNCTIONS,
    'HASHFLOW': HASHFLOW_FUNCTIONS,
    'MAVERICK': MAVERICK_FUNCTIONS,
    'ROCKETPOOL': ROCKETPOOL_FUNCTIONS,
    'TOKEN_CREATION': TOKEN_CREATION_FUNCTIONS,
    'GAMING': GAMING_PROTOCOLS
}